- name: Display MySQL Databases
  hosts: localhost
  vars:
    mysql_user: "user"
    mysql_password: "password"
  
  #Mysql user should have created with host '%'
  #Mysql user should have  Create, grant ,update and reload permission to create user, grant permission, to update superprivilege, to flush.
  #GRANT CREATE USER ON *.* TO 'user'@'%';
  #GRANT UPDATE, GRANT OPTION ON mysql.* TO 'user'@'host';
  #GRANT RELOAD ON *.* TO 'user'@'%';
  #FLUSH PRIVILEGES;
  
  tasks:
    - name: Install PyMySQL
      pip:
        name: pymysql
        state: present

    - name: Create MySQL user
      community.mysql.mysql_query:
        login_user: "{{mysql_user}}"
        login_password: "{{mysql_password}}"
        query: "CREATE USER 'site24x7'@'%' IDENTIFIED BY 'site24x7';"
      register: query1_result

    - name: Create MySQL user
      community.mysql.mysql_query:
        login_user: "{{mysql_user}}"
        login_password: "{{mysql_password}}"
        query: "GRANT SELECT ON mysql.* TO 'site24x7'@'%';"
      register: query1_result
 
    - name: Use mysql DB
      community.mysql.mysql_query:
        login_user: "{{mysql_user}}"
        login_password: "{{mysql_password}}"
        query: "use mysql"
      register: query3_result

    - name: Grant Replication privileges
      community.mysql.mysql_query:
        login_user: "{{mysql_user}}"
        login_password: "{{mysql_password}}"
        query: "UPDATE mysql.user SET Super_Priv='Y' WHERE user='site24x7' AND host='%';"
      register: query4_result

    - name: Flush privileges
      community.mysql.mysql_query:
        login_user: "{{mysql_user}}"
        login_password: "{{mysql_password}}"
        query: "FLUSH PRIVILEGES;"
      register: query5_result

