---
 - name: "Site24x7 check_updates Plugin Installation"
   hosts: all 
   become: yes

   tasks:    
  # Site24x7 check_updates Prerequisites Check

   - name: "Python3 Installation Check."
     command: "python3 --version"
     register: python_version_output
     ignore_errors: yes

   - name: "Installing Python if not found (for Debian/Ubuntu)."
     apt:
        name: python3
        state: present
     when: "not python_version_output.stdout and ansible_facts['os_family'] == 'Debian'"

   - name: "Installing Python if not found (for CentOS/RedHat)."
     yum:
        name: python3
        state: present
     when: "not python_version_output.stdout and ansible_facts['os_family'] == 'RedHat'"

   - name: "pip3 Installation Check."
     command: "pip3 --version"
     register: pip_version_output
     ignore_errors: yes

   - name: "Installing pip3 if not found (for Debian/Ubuntu)."
     apt:
        name: python3-pip
        state: present
     when: "not pip_version_output.stdout and ansible_facts['os_family'] == 'Debian'"

   - name: "Installing pip3 if not found (for RedHat/CentOS)."
     yum:
        name: python3-pip
        state: present
     when: "not pip_version_output.stdout and ansible_facts['os_family'] == 'RedHat'"

   - name: "Installing distro Python3 Package."
     pip:
        name: distro
        state: present
        executable: pip3
     ignore_errors: yes

   - name: "Site24x7 Agent Directory Check."
     stat:
      path: "/opt/site24x7/monagent/temp"
     register: agent_path_check

   - name: "Hosts with no Site24x7 Agent Directory"
     debug:
      msg: "Agent Directory not found"
     when: not agent_path_check.stat.exists


   - name: "Site24x7 Temp Plugins Directory Creation."
     file:
      path: "/opt/site24x7/monagent/temp/plugins/check_updates"
      state: directory
     when: agent_path_check.stat.exists

   - name: "Site24x7 Plugin Directory Check"
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/check_updates"
     register: plugin_path_check

   - name: "Download the Site24x7 check_updates Plugin Files."
     get_url:
        url: "{{ item }}"
        dest: "/opt/site24x7/monagent/temp/plugins/check_updates"
        mode: 0744
     loop: ["https://raw.githubusercontent.com/site24x7/plugins/master/check_updates/check_updates.py"]
     when: plugin_path_check.stat.exists
    
  # Site24x7 check_updates Python File Setup

   - name: "Site24x7 check_updates Python File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/check_updates/check_updates.py"
     register: check_updates_python_file_check

   - name: "Extracting Python3 Default Path."
     command: which python3
     register: python3_path

   - set_fact:
      actual_path: "{{ '#!'+python3_path.stdout }}"

   - name: "Setting the Default Python Path for the Site24x7 check_updates Plugin"
     lineinfile:
       path: "/opt/site24x7/monagent/temp/plugins/check_updates/check_updates.py"
       regexp: "#!"
       line: "{{actual_path}}"
     when: check_updates_python_file_check.stat.exists

   - name: "Checking the Site24x7 check_updates Plugin Output"
     shell: "python3 /opt/site24x7/monagent/temp/plugins/check_updates/check_updates.py"
     register: check_updates_python_output
     when: check_updates_python_file_check.stat.exists

   - name: "Site24x7 check_updates plugins with Error !"
     debug:
      msg: "Site24x7 check_updates Plugin OUTPUT error ! \n {{ check_updates_python_output.stdout }}"
     when: "'\"status\": 0' in check_updates_python_output.stdout and check_updates_python_file_check.stat.exists"

   - name: "Moving the Site24x7 check_updates Folder to the Plugins Directory"
     command: "mv  /opt/site24x7/monagent/temp/plugins/check_updates /opt/site24x7/monagent/plugins"
     ignore_errors: true
     when: "plugin_path_check.stat.exists and '\"status\": 0' not in check_updates_python_output.stdout"
