---
 - name: "Site24x7 apache_monitoring Plugin Installation"
   hosts: all 
   become: yes
   vars:
      apache_monitoring_url: "http://localhost:80/server-status?auto"
      apache_monitoring_username: "None"                           
      apache_monitoring_password: "None"    
      apache_monitoring_timeout: "30" 
      apache_monitoring_plugin_version: "1"    
      apache_monitoring_heartbeat: "true"
      apache_monitoring_logs_enabled: "true"
      apache_monitoring_log_type_name: "Apache Access Logs"
      apache_monitoring_log_file_path: "/var/log/apache*/access.log*"

  
   tasks:    
  # Site24x7 apache_monitoring Prerequisites Check

   - name: "Python3 Installation Check."
     command: "python3 --version"
     register: python_version_output
     ignore_errors: yes

   - name: "Installing Python if not found (for Debian/Ubuntu)."
     apt:
        name: python3
        state: present
     when: "not python_version_output.stdout and ansible_facts['os_family'] == 'Debian'"

   - name: "Installing Python if not found (for CentOS/RedHat)."
     yum:
        name: python3
        state: present
     when: "not python_version_output.stdout and ansible_facts['os_family'] == 'RedHat'"

   - name: "pip3 Installation Check."
     command: "pip3 --version"
     register: pip_version_output
     ignore_errors: yes

   - name: "Installing pip3 if not found (for Debian/Ubuntu)."
     apt:
        name: python3-pip
        state: present
     when: "not pip_version_output.stdout and ansible_facts['os_family'] == 'Debian'"

   - name: "Installing pip3 if not found (for RedHat/CentOS)."
     yum:
        name: python3-pip
        state: present
     when: "not pip_version_output.stdout and ansible_facts['os_family'] == 'RedHat'"

   - name: "Site24x7 Agent Directory Check."
     stat:
      path: "/opt/site24x7/monagent/temp"
     register: agent_path_check

   - name: "Hosts with no Site24x7 Agent Directory"
     debug:
      msg: "Agent Directory not found"
     when: not agent_path_check.stat.exists

   - name: "httpd Status Check"
     service:
        name: httpd
        state: started
     ignore_errors: yes
     when: "ansible_facts['os_family'] == 'RedHat'"

   - name: "apache Status Check"
     service:
        name: apache2
        state: started
     ignore_errors: yes
     when: "ansible_facts['os_family'] == 'Debian'"

   - name: "Site24x7 Temp Plugins Directory Creation."
     file:
      path: "/opt/site24x7/monagent/temp/plugins/apache_monitoring"
      state: directory
     when: agent_path_check.stat.exists

   - name: "Site24x7 Plugin Directory Check"
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/apache_monitoring"
     register: plugin_path_check

   - name: "Download the Site24x7 apache_monitoring Plugin Files."
     get_url:
        url: "{{ item }}"
        dest: "/opt/site24x7/monagent/temp/plugins/apache_monitoring"
        mode: 0744
     loop: ["https://raw.githubusercontent.com/site24x7/plugins/master/apache_monitoring/apache_monitoring.py","https://raw.githubusercontent.com/site24x7/plugins/master/apache_monitoring/apache_monitoring.cfg"]
     when: plugin_path_check.stat.exists
    

  # Site24x7 apache_monitoring Plugin Config File Setup

   - name: "Site24x7 apache_monitoring Config File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/apache_monitoring/apache_monitoring.cfg"
     register: apache_monitoring_file_check

   - name: "Site24x7 apache_monitoring configuration."
     lineinfile: 
       path: "/opt/site24x7/monagent/temp/plugins/apache_monitoring/apache_monitoring.cfg"
       regexp: "{{ item.regex }}"
       line: "{{ item.line }}"
     loop:
       - { regex: 'url =', line: 'url ="{{apache_monitoring_url}}"' }
       - { regex: 'username =', line: 'username ="{{apache_monitoring_username}}"' }
       - { regex: 'password =', line: 'password ="{{apache_monitoring_password}}"' }
       - { regex: 'timeout =', line: 'timeout ="{{apache_monitoring_timeout}}"' }
       - { regex: 'plugin_version =', line: 'plugin_version ="{{apache_monitoring_plugin_version}}"' }
       - { regex: 'heartbeat =', line: 'heartbeat ="{{apache_monitoring_heartbeat}}"' }
       - { regex: 'logs_enabled =', line: 'logs_enabled ="{{apache_monitoring_logs_enabled}}"' }
       - { regex: 'log_type_name =', line: 'log_type_name ="{{apache_monitoring_log_type_name}}"' }
       - { regex: 'log_file_path =', line: 'log_file_path ="{{apache_monitoring_log_file_path}}"' }

     when: apache_monitoring_file_check.stat.exists

  # Site24x7 apache_monitoring Python File Setup

   - name: "Site24x7 apache_monitoring Python File Check."
     stat:
      path: "/opt/site24x7/monagent/temp/plugins/apache_monitoring/apache_monitoring.py"
     register: apache_monitoring_python_file_check

   - name: "Extracting Python3 Default Path."
     command: which python3
     register: python3_path

   - set_fact:
      actual_path: "{{ '#!'+python3_path.stdout }}"

   - name: "Setting the Default Python Path for the Site24x7 apache_monitoring Plugin"
     lineinfile:
       path: "/opt/site24x7/monagent/temp/plugins/apache_monitoring/apache_monitoring.py"
       regexp: "#!"
       line: "{{actual_path}}"
     when: apache_monitoring_python_file_check.stat.exists

   - name: "Checking the Site24x7 apache_monitoring Plugin Output"
     shell: "python3 /opt/site24x7/monagent/temp/plugins/apache_monitoring/apache_monitoring.py --url=\"{{apache_monitoring_url}}\" --username=\"{{apache_monitoring_username}}\" --password=\"{{apache_monitoring_password}}\" --timeout=\"{{apache_monitoring_timeout}}\" --plugin_version=\"{{apache_monitoring_plugin_version}}\" --heartbeat=\"{{apache_monitoring_heartbeat}}\" --logs_enabled=\"{{apache_monitoring_logs_enabled}}\" --log_type_name=\"{{apache_monitoring_log_type_name}}\" --log_file_path=\"{{apache_monitoring_log_file_path}}\""
     register: apache_monitoring_python_output
     when: apache_monitoring_python_file_check.stat.exists

   - name: "Site24x7 apache_monitoring plugins with Error !"
     debug:
      msg: "Site24x7 apache_monitoring Plugin OUTPUT error ! \n {{ apache_monitoring_python_output.stdout }}"
     when: "'\"status\": 0' in apache_monitoring_python_output.stdout and apache_monitoring_python_file_check.stat.exists"

   - name: "Moving the Site24x7 apache_monitoring Folder to the Plugins Directory"
     command: "mv  /opt/site24x7/monagent/temp/plugins/apache_monitoring /opt/site24x7/monagent/plugins"
     ignore_errors: true
     when: "plugin_path_check.stat.exists and '\"status\": 0' not in apache_monitoring_python_output.stdout"
